insert into superhero (id, name) values  (1, 'Batman')
insert into superhero (id, name) values  (2, 'Spiderman')
insert into superhero (id, name) values  (3, 'Ironman')
insert into superhero (id, name) values  (4, 'Captain America')
insert into superhero (id, name) values  (5, 'Black Widow')